//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZimAdmin.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization_history
    {
        public long Id_Auth { get; set; }
        public int Id_Admin { get; set; }
        public System.DateTime Date_Auth { get; set; }
    
        public virtual Admins Admins { get; set; }
    }
}
